### ISSUE TITLE
Allow super admins to create admins

### ISSUE THREAD

**Issue by RobertWSaunders** [qhacks/qhacks-dashboard#110]
**Problem**
Add in registration functionality for admins

**Comment by RobertWSaunders** [comment]
lets bump this and focus on admin functionality for a bit

**Comment by rosslh** [comment]
let's push to `/feature/AdminRegistration` so we can test the front and back-end parts together

**Comment by RobertWSaunders** [comment]
My advice would be to work independantly and have two separate PR's, on for front end changes and one for backend. if you can rename your branch something like and `feature/admin-registration-client` and do a force push to rewrite history upstream that would be awesome, then either I or @joeytepp can start working on a `feature/admin-registration-server` PR

**Comment by RobertWSaunders** [comment]
Getting pretty stale, will make new issues for new deliverables!
