### ISSUE TITLE
Secure vital endpoints

### ISSUE THREAD

**Issue by RobertWSaunders** [qhacks/qhacks-dashboard#111]
**Problem**
Currently our endpoints are not secured /users is an example

**Comment by zackharley** [comment]
Maybe we can use https://github.com/isaacs/node-glob to match url patterns

**Comment by paulxuca** [comment]
Makes more sense to use route specific middleware to secure endpoints - fits more into the traditional router middleware pattern in express/koa/etc.

**Comment by RobertWSaunders** [comment]
We are using a new GraphQL API, as a result this is stale!

**Comment by RobertWSaunders** [comment]
We've also added different authorization levels via resources scopes to address this in our GQL api.
