### ISSUE TITLE
Add cross platform support for Windows to dev environment

### ISSUE THREAD

**Issue by joeytepp** [qhacks/qhacks-dashboard#122]
## Problem
Can't run the dashboard locally on PC. Debug Log attached
[npm-debug.log](https://github.com/qhacks/hacker-dashboard/files/1935912/npm-debug.log)

**Comment by RobertWSaunders** [comment]
@joeytepp now that you are on mac can we close this?

Also quick tip, a more descriptive title would be better, cross platform support for what...?

**Comment by joeytepp** [comment]
@RobertWSaunders i'm planning on switching my pc for a mac at the end of the summer but gonna keep this open until then

**Comment by joeytepp** [comment]
Looks like we can close this now 🎉

**Comment by RobertWSaunders** [comment]
👍
