### ISSUE TITLE
Provide more descriptive error messages on the client

### ISSUE THREAD

**Issue by rosslh** [qhacks/qhacks-dashboard#123]
## Problem
When applying, if you enter an email that has already been used in an application, the submission is (appropriately) rejected as invalid. However, the error message at the bottom of the page just says "Your application is invalid!" without any further details.

## Expected Behavior
The error message should say _why_ your application is invalid. In most cases it does this, just not with a duplicate email.

## Steps to Reproduce the Problem

1. go to /apply
2. submit the form with an email already used by another user
3. take a look at the (lack of a descriptive) error message

**Comment by RobertWSaunders** [comment]
I think this is linked to #56, i think there just needs to be better error handling across the board on the client.

**Comment by RobertWSaunders** [comment]
Improvements have been made on this! Because we've rewrote most of our client I'm going to close this!
