### ISSUE TITLE
New Data Layer Proposal

### ISSUE THREAD

**Issue by RobertWSaunders** [qhacks/qhacks-dashboard#153]
## Summary

As we look to ramp up development for this years dashboard I took sometime to revisit our database design. We cobbled the database together pretty fast last year with little consideration for design and as a result we are now hurting because of it. Here I have outlined some changes I would like to make to the data layer and wanted to run it by you guys as I work on it. See the proposed data structures for the new design and a summary of the core changes in those structures. I have left some open questions at the bottom of this report as well.

**User Model Changes**

Proposed data structure for a hacker in the database:

```json
{
  "_id": "123",
  "firstName": "Robert",
  "lastName": "Saunders",
  "email": "bob@bob.com",
  "phoneNumber": "4166057919",
  "dateOfBirth": "2018-01-22T04:45:53.532+0000",
  "gender": "Male",
  "password": "password",
  "createdAt": "2018-01-22T04:45:53.532+0000",
  "modifiedAt": "2018-01-22T04:45:53.532+0000",
  "passwordResetHash": "1234",
  "refreshToken": "1234",
  "role": "HACKER",
  "school": "Queen's University",
  "degreeType": "Bachelor's",
  "program": "A program",
  "graduationYear": "2019",
  "graduationMonth": "December",
  "applications": [
    {
      "_id": "1234",
      "event": "12345",
      "applicationStatus": "ACCEPTED",
      "rsvpStatus": "PENDING",
      "checkInStatus": "PENDING",
      "applicationFields": {
        "dietaryRestrictions": "None",
        "emergencyContactEmail": "",
        "emergencyContactFirstName": "",
        "emergencyContactLastName": "",
        "emergencyContactPhoneNumber": "",
        "emergencyContactRelationship": "",
        "favouriteSnack": "",
        "resume": "",
        "tshirtSize": "",
        "travelOrigin": "",
        "hackathonCount": "",
        "whyQHacks": "",
        "links": "",
        "createdAt": "",
        "modifiedAt": "",
        "reviews": [
          {
            "_id": "1234",
            "reviewer": "1234",
            "score": "2",
            "createdAt": "2018-01-22T04:45:53.532+0000",
            "modifiedAt": "2018-01-22T04:45:53.532+0000"
          }
        ]
      }
    }
  ]
}
```

Core changes outlined here:

- Change `relation` of emergency contact to be `relationship`.
- Change `status` in an application to be `applicationStatus`.
- Change `rsvp` in an application to be `rsvpStatus`.
- Change `checkIn` to be `checkInStatus`.
- Change `numberOfHackathons` to be `hackathonCount`.
- Change `performedBy` to be `reviewer`.
- Within an application encapsulate an form fields inside `applicationFields`.

The real thing to focus on here is just new addition of `applicationFields`.

**Event Model Changes**

This is where a big change will be made, focus your attention on this!

```json
{
  "_id": "12345",
  "name": "QHacks 2018",
  "slug": "qhacks-2018",
  "applicationRequired": "true",
  "applicationsOpen": "false",
  "reviewsPerApplicationRequired": 3,
  "applicationFields": [
    {
      "name": "Dietary Restrictions",
      "type": "String",
    },
    {
      "name": "Emergency Contact Email",
      "type": "String",
    },
    {
      "name": "Emergency Contact First Name",
      "type": "String",
    },
    {
      "name": "Emergency Contact Last Name",
      "type": "String",
    },
    {
      "name": "Emergency Contact Phone Number",
      "type": "String"
    },
    {
      "name": "Emergency Contact Relationship",
      "type": "String"
    },
    {
      "name": "Favourite Snack",
      "type": "String"
    },
    {
      "name": "Resume",
      "type": "String"
    },
    {
      "name": "T-Shirt Size",
      "type": "Selection",
      "options": [
        "SMALL",
        "MEDIUM",
        "LARGE"
      ]
    },
    {
      "name": "Travel Origin",
      "type": "String"
    },
    {
      "name": "Hackathon Count",
      "type": "Integer"
    },
    {
      "name": "Why QHacks",
      "type": "String"
    },
    {
      "name": "Links",
      "type": "String"
    },
  ]
}
```

Core changes outlined here:

- Add `applicationRequired` to allow admins to configure if applications are required for the event.
- Add `applicationsOpen` to allow admins to toggle applications on a per event basis.
- Add `reviewsPerApplicationRequired` to allow admins to require applications to have a specific number of reviews. This is to replace the global setting we have in the settings model. The reason this felt right was because the admins can now configure it on an per event basis.
- Add `applicationFields` that allows admins to create form fields for the event application. Having our application form fields in our schema felt weird because its not configurable for other types of events. In addition, if in the future we need to add a new field to the application form then we'd have to do it by code. Storing application fields in the database and having admins create them will enable us to render a form based on the fields they created with no code changes at all! Now you should be able to see why having a similar `applicationFields` in the user model makes sense. In Mongoose it will be a Mixed type so that the fields can be named based off of the fields the admins want in their application form field.

### Questions

Do the names of the new fields make sense?

Do you think this is a good change?

Does this change make sense?

### Motivation

Improve configuration and store our data better!

**Comment by joeytepp** [comment]
Very much like these changes, one concern I have is regarding the relationship between the `Event` model and the `applications` field for the `User` model. Do you think that events should be able to  define new application fields, or we should limit them to existing ones in the existing application schema? I'd assume that if we're limiting to existing fields then the `name` and `type` fields of the `applicationFields` schema would be enumerable? Also do we want to include some required fields for all applications of all events or should it be entirely on an event-by-event basis? Just some thoughts that I was having regarding these changes, overall I am definitely in favour

**Comment by RobertWSaunders** [comment]
Good questions, see my answers below:

> Do you think that events should be able to define new application fields, or we should limit them to existing ones in the existing application schema?

I like the idea of having application fields being a configurable option for admins on a per event basis. The reason is because on the front end I want to do some cool stuff to accompany it. Such as, instead of having one `app.qhacks.io/apply` I want to make event urls like `app.qhacks.io/qhacks-2018/apply` or something. This will allow us to have multiple event forms open at the same time and different events can have different forms to apply. I see this useful if we want to have things like campus workshops sign ups, or local hack day sign ups, or hiring event to go through the dashboard. Turning the dashboard into something that you have an account in and can manage all the QHacks events you've been to is the goal we going for. Even if we don't adopt that new stuff on the front end just yet because they come with their own challenges at least we'll have the backend to support it. 

> I'd assume that if we're limiting to existing fields then the name and type fields of the applicationFields schema would be enumerable?

I think having `type` be enumerable makes sense because there is a finite number of field types we can render on the front end. The name though I think should be anything, because for the reasons mentioned above, the field names will be chosen by admins and stored in the database in the `applicationFields` subdocument using those names.

> Also do we want to include some required fields for all applications of all events or should it be entirely on an event-by-event basis?

This is something I haven't thought about, but with this design we can just add those fields into the event on event creation, so nothing we have to change here if we wanted to do that!

Nice questions, let me know what you think!

**Comment by joeytepp** [comment]
Nice nice, I like the vision going forward! This would most likely mean changes to the `application` schema as well then, guess we will see!

**Comment by rosslh** [comment]
These changes make sense to me. In particular, `applicationFields` should make creating new events a lot faster in the future. Looks good!

**Comment by joeytepp** [comment]
Once these changes go through we should create some new routes on the server for `events` specifically (ie `events.routes.js`). Would include a fix for #129 as well. Will start on that once these changes go through

**Comment by joeytepp** [comment]
Also @RobertWSaunders @rosslh do you think events should have a `description` field as well? Would be good for workshops

**Comment by RobertWSaunders** [comment]
Sounds good @joeytepp, I was actually going include some updated routes in my change as well! But you can definitely add some more in as well. I definitely think events should have a `description` field! 

Which name do you think is better, `applicationFields` or `applicationFormFields`?

**Comment by joeytepp** [comment]
Probably `applicationFormFields`, also, how do we want to go about converting the names to valid fields for mongoose? Do we want to convert them to camelcase or would it be worth having a `slug` field or something similar within the `applicationFormFields`?

**Comment by RobertWSaunders** [comment]
Agreed, we'll camelcase them!

**Comment by RobertWSaunders** [comment]
No longer using Mongo! Stale issue!
