### ISSUE TITLE
QHacks dashboard front-end feedback

### ISSUE THREAD

**Issue by rosslh** [qhacks/qhacks-dashboard#180]
### Landing pages

- [x] All caps menu items
- [x] Fix landing image
- [ ] Menu items underline animation
- [ ] Menu dropdown
- [x] Make thinner version of ActionButton (inline?)
- [x] Add border to right of landing sidebar
- [x] Give inputs a dropshadow
- [x] Remove input side margin
- [x] Fix landing background color
- [x] Switch wordmark to image
- [ ] Make checkbox color customizable
- [x] Make landing page links bold and underlined and grey and aligned right
- [x] Give ActionButton boxshadows
- [ ] Deal with focus outlines (blue border on focus?)
- [x] Give inputs max width
- [x] Reduce landing page padding/margins
- [x] Reduce landing page paragraph width and increase font size
- [x] Create status component (success, caution, info, error) with close button

### Apply form

- [x] Apply form background is zoomed in
- [x] Change menu for apply form before and after auth
- [x] Make form header text black and all caps
- [ ] Look into header text sizing
- [x] Make all apply form headings grey/black
- [x] Fix slider and nav font weight
- [x] Fix application nav checkbox vertical alignment
- [x] Apply steps should be capitalized
- [x] Fix slider border-width and color
- [x] Create account font size too low
- [x] Shrink form width
- [x] Add form placeholders
- [x] Labels should be grey, capitalized, bold
- [x] Fix form bottom margin
- [x] Add terms and conditions & privacy policy links to apply form
- [x] Missing a line between form sections
- [x] Form section titles too bold and not capitalized
- [x] Fix default font weights
- [ ] Add arrow and right align continue button
- [x] Remove previous button from step 2 and step 4
- [x]  Invalid form should result in disabled continue button
- [x] Change prev. button to "Back" and make black
- [x] Fix input height to match up with react-select
- [x] Add space below bottom of form
- [ ] Add red star for required fields
- [x] Make num hackathon input smaller
- [x] All around tweaks to step 4 content

### Modal component
- [x] Create modal component to show TOS and privacy policy

----

## Sat Dec 1

- [x] Add remaining form questions
> Tell us about a time you brought a dream or passion project of yours to life. (< 300 words)
> What about QHacks has driven you to apply this year? (< 300 words)
> You're given $10,000 to spend on building a project or running an event at QHacks this year. What do you spend it on? (< 100 words) 
- [x] Style MLH checkboxes and labels nicely
- [x] Make sure form validation and hacker slider work well together
- [x] Fix landing page image
- [x] Add Forgot Password link to apply form login

**Comment by RobertWSaunders** [comment]
For the rest of these items I'm going to make individual issues so that they can be treated in individual PRs!
