### ISSUE TITLE
Add Slack bot to dashboard

### ISSUE THREAD

**Issue by joeytepp** [qhacks/qhacks-dashboard#230]
## Summary
Create a slack bot and add it to the existing codebase of the dashboard

Brief explanation of the feature.
The slack bot should have the following capabilities
- [ ] Greet hackers when they join the slack
- [ ] Notify hackers about activities
- [ ] Ask hackers that checked in for feedback after activities
- [ ] Provide an interface for allowing Admins to send out custom slack messages

### Motivation
For better interaction with hackers during the event

Why are we doing this? What use cases does it support? What is the expected outcome?
Allows us to send notifications without sending desktop notifications, makes us rely less on people actively using the dashboard during the event

**Comment by RobertWSaunders** [comment]
@joeytepp How you thinking of implementing this?
