### ISSUE TITLE
Allow hackers to edit their application

### ISSUE THREAD

**Issue by zackharley** [qhacks/qhacks-dashboard#79]
**Problem**
Hackers cannot currently edit their applications

**Requirements**
- [ ] Add a tab to the dashboard allowing hackers to edit their application

**Comment by RobertWSaunders** [comment]
This should be a high priority for next year.

**Comment by RobertWSaunders** [comment]
Never got around to it! @joeytepp @rosslh 😢 Stale issue with new rewrite of dashboard!
