### ISSUE TITLE
Make UserModel more scalable

### ISSUE THREAD

**Issue by zackharley** [qhacks/qhacks-dashboard#88]
**Problem**
UserModel has some disjointed properties. We should clean it up to make it more scalable.

**Requirements**
Update the UserModel in a manner similar to this (use [Mongoose discriminators](http://mongoosejs.com/docs/discriminators.html)):
```js
const Review = new mongoose.Schema({ ... });
const ApplicationSchema = new mongoose.Schema({
  reviews: [ReviewSchema],
  ...
});

const PersonaSchema = new mongoose.Schema({
  event: <ref Events collection>
});

const AdminSchema = new mongoose.Schema({
  goldenTickets,
  reviewGroup,
  role,
  ...
});
const HackerSchema = new mongoose.Schema({
  role,
  /*
   * The below fields are currently stored on the main level of the UserSchema,
   * but should be moved to a specific application as they can change from year
   * to year.
   */
  travelOrigin,
  numberOfHackathons,
  links,
  whyQhacks,
  ...
});
const PartnerSchema = new mongoose.Schema({ 
  role,
  ...
});

const UserSchema = new mongoose.Schema({
  // Use discriminators to "inherit" PersonaSchema
  // Need a better name for this array
  personas: [AdminSchema | HackerSchema | PartnerSchema], 
  ...
});
```

**Note:**  `...` represents the current properties of the schema

**Comment by RobertWSaunders** [comment]
@joeytepp this could be related to #97, might be good to investigate.

**Comment by joeytepp** [comment]
@RobertWSaunders gonna get started on this once #131 merges, I wanna add in some unit tests as well

**Comment by RobertWSaunders** [comment]
We can close this now that we use discriminators thanks to @joeytepp! See https://github.com/qhacks/qhacks-dashboard/pull/143
